leftnav:
- identifier: f9d8d4f2-1c50-78aa-5d1c-6574090701be
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: ee99e633-8b50-71a7-dbb3-c9069a6a437c
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: a5a96ca7-3785-bed6-3324-a796fe1914b8
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 7228f652-062f-993c-530c-35c7e8d3b159
  name: Projects
  url: /pages/projects
  weight: 40
